- name: Manage Linux packages
  hosts: web_servers
  become: true
  vars:
    packages:
      - vim
      - curl
      - git

  tasks:
    - name: Update apt cache
      ansible.builtin.apt:
        update_cache: true
      when: ansible_facts['os_family'] == "Debian"

    - name: Install required packages
      ansible.builtin.package:
        name: "{{ packages }}"
        state: present
        